"""Imports every model module so `Base.metadata` is complete.

Alembic only sees a table whose module has been imported, and cross-module foreign
keys fail to resolve without this — verified: importing `patients.models` alone and
emitting its DDL raises `NoReferencedTableError` because `users` is unregistered.
Without this single import site, a forgotten import produces an autogenerated
migration that silently drops tables. Import this module — never individual model
modules — from `migrations/env.py`.
"""

from __future__ import annotations

from app.db.base import Base
from app.modules.identity import models as identity_models  # noqa: F401
from app.modules.patients import models as patient_models  # noqa: F401
from app.modules.providers import models as provider_models  # noqa: F401
from app.modules.scheduling import models as scheduling_models  # noqa: F401

#: Every table name registered on the shared metadata, for assertions and tooling.
ALL_TABLES = set(Base.metadata.tables)

__all__ = ["ALL_TABLES", "Base"]
