"""Renders the catalog and traceability reports from a routing result.

Both files are generated, never hand-edited. `traceability.md` answers the
assignment's "traceability between features and deliverables" requirement from
test data rather than a hand-maintained table.
"""

from __future__ import annotations

from collections import Counter, defaultdict

from tests.runner.discover import Routing, unsupported_kinds
from tests.runner.schema import Case

GENERATED_BANNER = (
    "<!-- Generated by `python -m tests.runner.route_check --write-catalog`. "
    "Do not edit by hand. -->"
)


def _bucket_of(case: Case, routing: Routing) -> str:
    if case in routing.blocked:
        return "blocked"
    if case in routing.unsupported:
        return "engine-unsupported"
    if case in routing.impl_backed:
        return "impl"
    return "declarative"


def render_catalog(routing: Routing) -> str:
    cases = sorted(routing.all_cases, key=lambda case: case.id)
    by_tier = Counter(case.tier for case in cases)
    by_priority = Counter(case.priority for case in cases)

    lines = [
        GENERATED_BANNER,
        "",
        "# Test Case Catalog",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | --- |",
        f"| Total cases | {len(cases)} |",
    ]
    for tier, count in sorted(by_tier.items()):
        lines.append(f"| {tier} | {count} |")
    for priority, count in sorted(by_priority.items()):
        lines.append(f"| {priority} | {count} |")
    lines += [
        f"| declarative | {len(routing.declarative)} |",
        f"| impl-backed | {len(routing.impl_backed)} |",
        f"| engine-unsupported | {len(routing.unsupported)} |",
        f"| blocked | {len(routing.blocked)} |",
        "",
        "## Cases",
        "",
        "| id | tier | priority | execution | requirement | title |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for case in cases:
        requirement = ", ".join(case.requirement) or "—"
        lines.append(
            f"| {case.id} | {case.tier} | {case.priority} | {_bucket_of(case, routing)} "
            f"| {requirement} | {case.title} |"
        )

    if routing.blocked:
        lines += ["", "## Blocked cases", "", "| id | reason |", "| --- | --- |"]
        for case in sorted(routing.blocked, key=lambda c: c.id):
            lines.append(f"| {case.id} | {case.blocked_on} |")

    if routing.unsupported:
        lines += [
            "",
            "## Engine-unsupported cases",
            "",
            "These are authored but reference a step or expectation kind with no handler yet.",
            "They FAIL when run — that is deliberate. Implement the handler, or mark the case",
            "blocked with a reason.",
            "",
            "| id | missing |",
            "| --- | --- |",
        ]
        for case in sorted(routing.unsupported, key=lambda c: c.id):
            lines.append(f"| {case.id} | {', '.join(sorted(unsupported_kinds(case)))} |")

    return "\n".join(lines) + "\n"


def render_traceability(cases: list[Case]) -> str:
    by_requirement: dict[str, list[str]] = defaultdict(list)
    for case in sorted(cases, key=lambda case: case.id):
        for requirement in case.requirement or ["(none)"]:
            by_requirement[requirement].append(case.id)

    lines = [
        GENERATED_BANNER,
        "",
        "# Requirement Traceability",
        "",
        "Each PRD requirement id and the cases that cover it. `(none)` collects cases that",
        "declare no requirement — every one of those is a traceability gap to close.",
        "",
        "| requirement | cases | count |",
        "| --- | --- | --- |",
    ]
    for requirement in sorted(by_requirement, key=lambda key: (key == "(none)", key)):
        ids = by_requirement[requirement]
        lines.append(f"| {requirement} | {', '.join(ids)} | {len(ids)} |")
    return "\n".join(lines) + "\n"
