"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-02 16:40:30.696830
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required by the provider_slots exclusion constraint below.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinics')),
    sa.UniqueConstraint('name', name=op.f('uq_clinics_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'provider', 'front_desk', 'admin', name='userrole', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('departments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_departments_clinic_id_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('clinic_id', 'name', name='uq_departments_clinic_id_name')
    )
    op.create_index(op.f('ix_departments_clinic_id'), 'departments', ['clinic_id'], unique=False)
    op.create_table('patients',
    sa.Column('mrn', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patients_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patients_user_id'))
    )
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_table('providers',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_providers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('license_number', name=op.f('uq_providers_license_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_providers_user_id'))
    )
    op.create_index(op.f('ix_providers_specialty'), 'providers', ['specialty'], unique=False)
    op.create_table('provider_departments',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_provider_departments_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_departments_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'department_id', name=op.f('pk_provider_departments'))
    )
    op.create_table('provider_slots',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('free', 'held', 'booked', 'blocked', name='slotstatus', native_enum=False, create_constraint=True, length=16), server_default=sa.text("'free'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_provider_slots_end_after_start')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_provider_slots_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_provider_slots_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_slots_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_slots'))
    )
    op.create_index('ix_provider_slots_provider_starts', 'provider_slots', ['provider_id', 'starts_at'], unique=False)
    op.create_index('ix_provider_slots_status_starts', 'provider_slots', ['status', 'starts_at'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'fulfilled', 'expired', 'cancelled', name='waitliststatus', native_enum=False, create_constraint=True, length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_waitlist_entries_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_waitlist_entries_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_waitlist_entries_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist_entries'))
    )
    op.create_index(op.f('ix_waitlist_entries_patient_id'), 'waitlist_entries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_status'), 'waitlist_entries', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'rescheduled', 'completed', 'no_show', 'failed', name='appointmentstatus', native_enum=False, create_constraint=True, length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rescheduled_from_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_appointments_clinic_id_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_appointments_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_appointments_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], name=op.f('fk_appointments_rescheduled_from_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['provider_slots.id'], name=op.f('fk_appointments_slot_id_provider_slots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_patient_status', 'appointments', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_provider_id'), 'appointments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('visits',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('checked_in', 'in_progress', 'completed', name='visitstatus', native_enum=False, create_constraint=True, length=16), server_default=sa.text("'checked_in'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_visits_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_visits_appointment_id'))
    )
    # ### end Alembic commands ###

    # A provider cannot have two overlapping slots. Without this a buggy slot
    # generator silently produces double-bookable inventory; with it, the bad write
    # fails immediately.
    op.execute(
        """
        ALTER TABLE provider_slots
          ADD CONSTRAINT ck_provider_slots_no_overlap
          EXCLUDE USING gist (
            provider_id WITH =,
            tstzrange(starts_at, ends_at) WITH &&
          )
        """
    )

    # At most one *live* appointment may hold a slot. This makes the invariant a
    # database guarantee rather than a consequence of the booking activity being
    # written correctly. Partial, so cancelling frees the slot again.
    op.execute(
        """
        CREATE UNIQUE INDEX ux_appointments_live_slot
            ON appointments (slot_id)
         WHERE status IN ('pending', 'confirmed') AND slot_id IS NOT NULL
        """
    )

    # `onupdate=func.now()` is a SQLAlchemy-level construct: verified against this
    # database, it fires for an ORM flush but NOT for a raw `text("UPDATE ...")`.
    # Week 2's booking activity claims a slot with exactly such a raw conditional
    # UPDATE, so without this trigger `updated_at` would go silently stale on the
    # single most important write in the system.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in (
        "users", "patients", "providers", "clinics", "departments",
        "provider_slots", "appointments", "visits", "waitlist_entries",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
            """
        )


def downgrade() -> None:
    for table in (
        "users", "patients", "providers", "clinics", "departments",
        "provider_slots", "appointments", "visits", "waitlist_entries",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.execute("DROP INDEX IF EXISTS ux_appointments_live_slot")
    op.execute(
        "ALTER TABLE provider_slots DROP CONSTRAINT IF EXISTS ck_provider_slots_no_overlap"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_provider_id'), table_name='appointments')
    op.drop_index('ix_appointments_patient_status', table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_waitlist_entries_status'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_patient_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index('ix_provider_slots_status_starts', table_name='provider_slots')
    op.drop_index('ix_provider_slots_provider_starts', table_name='provider_slots')
    op.drop_table('provider_slots')
    op.drop_table('provider_departments')
    op.drop_index(op.f('ix_providers_specialty'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_departments_clinic_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('clinics')
    # ### end Alembic commands ###
