"""Identifier generation.

UUIDv7 primary keys, per RFC 9562 §5.7.

**Why not v4.** A v4 key is entirely random, so inserts scatter across the whole
B-tree: pages split, cache locality is poor, and the index grows faster than it needs
to. A v7 key is time-ordered in its leading 48 bits, so inserts append near the right
edge of the index the way a sequence would -- while still being generated by the
application, before any database round trip, which is what keeps ids stable inside a
Kafka event payload and free of sequence contention.

**Why hand-rolled.** `uuid.uuid7()` arrives in the standard library in Python 3.14;
this project targets 3.13. Rather than take a dependency for fifteen lines against a
precise specification, this is a shim with an explicit removal path: when the floor
moves to 3.14, delete this and alias `uuid.uuid7`. The layout is verified by tests
that assert the version nibble, the variant bits, and time ordering.

**The tradeoff, stated rather than assumed.** RFC 9562 §8 is explicit:

    "Timestamps embedded in the UUID do pose a very small attack surface ... If
    UUIDs are required for use with any security operation within an application
    context in any shape or form, then UUIDv4 SHOULD be utilized."

A v7 id therefore leaks its own creation time, and ids minted close together sort
close together. In this system record ids appear in URLs, so "when was this patient
registered" is inferable from the id alone. Accepted because 74 bits remain random
(brute force is infeasible) and every endpoint is role-gated, so an id is never a
capability -- knowing one grants nothing without a token. **If an id ever becomes a
bearer of authority -- a share link, a password-reset token, an unauthenticated
lookup -- it must use `uuid.uuid4()` instead, not this.**
"""

from __future__ import annotations

import secrets
import time
import uuid

__all__ = ["uuid7"]

#: RFC 9562 §5.7 field offsets, counted from the most significant bit of the 128-bit
#: value. unix_ts_ms occupies bits 0-47, so it is shifted left by the 80 bits that
#: follow it; ver occupies 48-51; rand_a 52-63; var 64-65; rand_b 61-0.
_TIMESTAMP_SHIFT = 80
_VERSION_SHIFT = 76
_RAND_A_SHIFT = 64
_VARIANT_SHIFT = 62

_VERSION = 0b0111  # 7
_VARIANT = 0b10  # RFC 9562 §4.1
_TIMESTAMP_MASK = (1 << 48) - 1


def uuid7(*, now_ms: int | None = None) -> uuid.UUID:
    """A UUIDv7: 48-bit millisecond timestamp, then 74 bits of randomness.

    `now_ms` is **keyword-only, deliberately**. SQLAlchemy decides how to invoke a
    column default by inspecting its signature: a callable it believes accepts one
    positional argument is handed the `ExecutionContext`, and only a callable it
    believes takes none is wrapped and called bare. With `now_ms` positional-capable
    that judgement rests on an arity heuristic -- it happens to wrap correctly today
    because the parameter is optional, but making it required would silently pass an
    `ExecutionContext` in as `now_ms`, and `context & mask` is a `TypeError` at the
    first insert. Keyword-only removes the question: this takes zero positional
    arguments, so there is nothing for SQLAlchemy to guess about.

    It exists so a test can pin the timestamp and assert ordering without patching
    the clock. It is deliberately *not* the injectable `Clock` from
    `app.core.clock`: a column default is called with no request context, so there is
    nowhere to thread a Clock through. Harness requirement 6 targets business logic
    that reasons about time -- slot windows, token expiry, wait-time analytics -- not
    identifier generation, whose timestamp is never read back or compared.

    `secrets` rather than `random`: the randomness here is what prevents collisions
    between two ids minted in the same millisecond, and a seeded PRNG shared across
    processes would silently defeat that.
    """
    timestamp = now_ms if now_ms is not None else time.time_ns() // 1_000_000

    value = (timestamp & _TIMESTAMP_MASK) << _TIMESTAMP_SHIFT
    value |= _VERSION << _VERSION_SHIFT
    value |= secrets.randbits(12) << _RAND_A_SHIFT
    value |= _VARIANT << _VARIANT_SHIFT
    value |= secrets.randbits(62)

    return uuid.UUID(int=value)
